// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfukrqpcbnfdzemiamex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmdWtycXBjYm5mZHplbWlhbWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDkxODYsImV4cCI6MjA1OTk4NTE4Nn0.9xH3LR6UaYdkqydA77RXczZ68kF_edAA1OBGhesAtnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);